name: tastebooster
description: A new Flutter project.

publish_to: "none"

version: 1.0.3+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  assets_audio_player: ^2.0.13+1
  cupertino_icons: ^1.0.0
  flutter_tindercard: ^0.1.7
  google_fonts: ^1.1.1
  json_annotation: ^3.1.0
  overlay_support: ^1.0.5
  package_info: ^0.4.3+2
  path_provider: ^1.6.24
  provider: ^4.3.2+2
  sentry: ">=3.0.0 <4.0.0"
  shared_preferences: ^0.5.12+4
  spotify_sdk: ^1.0.0
  sqflite: ^1.3.2+1
  url_launcher: ^5.7.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.4
  flutter_launcher_icons: ^0.8.1
  json_serializable: ^3.5.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/tastebooster_logo_barcode.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/
